### ISSUE TITLE
Bug Report: Glitch Between /home and /login Pages on logout Redirect

### ISSUE THREAD

**Issue by jamaljm** [jamaljm/snapcv#5]
**Describe the Bug**

When logging out, the application redirects between the /home and /login pages with a noticeable glitch. The transition between these pages is not smooth, and it appears as though the user is briefly sent back to /home before landing on /login.

**To Reproduce**

1. Log in to the application.
2. Click on the 'Logout' button.
3. Observe the redirect behavior.

**Expected Behavior**

After clicking the 'Logout' button, the application should immediately redirect to the /login page without any visual glitches or redirections back to the /home page.

**Comment by Jamie-19** [comment]
this is a minor bug and i beleive i can solve it
